name: Initialize Template

on:
  push:
    branches:
      - main
      - master

jobs:
  publish:
    name: Initialize Template
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'cpdevtools/template-generate-template' }}
    steps:
      - uses: actions/checkout@v3
      - uses: cpdevtools/action-template@dev
        with:
          action: init-tpl
