name: Test

on:
  push:
    branches:
      - "*"

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'cpdevtools/template-generate-template' }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.2.0

      - name: Install Node & Dependencies
        uses: ./.github/actions/setup-node

      - name: Build
        uses: ./.github/actions/build

      - name: Run Tests
        uses: ./.github/actions/test
